### ISSUE TITLE
Error when using click 8.0.0

### ISSUE THREAD

**Issue by rly** [j0057/github-release#62]
Click 8.0.0 was released yesterday and `ProgressBar.length_known` is no longer an attribute.

The following command raises an error:
```
#!/bin/bash -eo pipefail
python -m venv ../venv
. ../venv/bin/activate
pip install githubrelease
githubrelease release $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
  create $CIRCLE_TAG --name $CIRCLE_TAG \
  --publish ./dist/*
```
Output (from CircleCI):
```
Collecting githubrelease
  Downloading githubrelease-1.5.8-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: requests in /home/circleci/venv/lib/python3.8/site-packages (from githubrelease) (2.25.1)
Collecting click
  Downloading click-8.0.0-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 14.4 MB/s eta 0:00:01
Collecting linkheader
  Downloading LinkHeader-0.4.3.tar.gz (4.2 kB)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/circleci/venv/lib/python3.8/site-packages (from requests->githubrelease) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/circleci/venv/lib/python3.8/site-packages (from requests->githubrelease) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/circleci/venv/lib/python3.8/site-packages (from requests->githubrelease) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/circleci/venv/lib/python3.8/site-packages (from requests->githubrelease) (2020.12.5)
Using legacy 'setup.py install' for linkheader, since package 'wheel' is not installed.
Installing collected packages: click, linkheader, githubrelease
    Running setup.py install for linkheader ... - done
Successfully installed click-8.0.0 githubrelease-1.5.8 linkheader-0.4.3
WARNING: You are using pip version 20.2.3; however, version 21.1.1 is available.
You should consider upgrading via the '/home/circleci/venv/bin/python -m pip install --upgrade pip' command.
created '2.5.3' release
  Tag name      : 2.5.3
  Name          : 2.5.3
  ID            : 42874007
  Created       : 2021-05-12T22:58:44Z
  URL           : https://github.com/hdmf-dev/hdmf/releases/tag/2.5.3
  Author        : ********
  Is published  : True
  Is prerelease : False

uploading '2.5.3' release asset(s) (found 2):
  uploading ./dist/hdmf-2.5.3.tar.gz
Traceback (most recent call last):
  File "/home/circleci/venv/bin/githubrelease", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/venv/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/home/circleci/venv/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/circleci/venv/lib/python3.8/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/circleci/venv/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/circleci/venv/lib/python3.8/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 437, in cli_release_create
    gh_release_create(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 469, in gh_release_create
    gh_asset_upload(repo_name, tag_name, asset_pattern, dry_run=dry_run)
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 116, in with_check_for_credentials
    return func(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 759, in gh_asset_upload
    already_uploaded, uploaded, _ = _upload_release_file(
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 699, in _upload_release_file
    with progress_reporter_cls(
  File "/home/circleci/venv/lib/python3.8/site-packages/click/_termui_impl.py", line 98, in __enter__
    self.render_progress()
  File "/home/circleci/venv/lib/python3.8/site-packages/click/_termui_impl.py", line 242, in render_progress
    line = self.format_progress_line()
  File "/home/circleci/venv/lib/python3.8/site-packages/click/_termui_impl.py", line 193, in format_progress_line
    info_bits.append(self.format_pos())
  File "/home/circleci/venv/lib/python3.8/site-packages/github_release.py", line 141, in formatPos
    if _self.length_known:
AttributeError: 'ProgressBar' object has no attribute 'length_known'
```

See https://github.com/pallets/click/pull/1856 for the change. I did not look into it further to see how this might be replaced in github-release.

**Comment by jcfr** [comment]
Thanks for the detailed report, this is very helpful. I will have a look asap (likely tomorrow) and submit a PR.
